# Generated by Django 3.2.13 on 2022-08-18 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('ADM', 'Administrator'), ('DOC', 'Lekarz'), ('PAT', 'Pacjent')], default='PAT', max_length=3)),
                ('pesel', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=40)),
                ('telephoneNumber', models.IntegerField(blank=True)),
                ('street', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('zipCode', models.CharField(max_length=6)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('taken', models.BooleanField(default=False)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Przychodnia.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=300, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Przychodnia.customer')),
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Przychodnia.term')),
            ],
        ),
        migrations.CreateModel(
            name='SpecializationDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Przychodnia.customer')),
                ('specializations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Przychodnia.specialization')),
            ],
        ),
    ]
