# Generated by Django 3.2.13 on 2022-08-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Przychodnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='room',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
