# Generated by Django 3.2.13 on 2022-08-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Przychodnia', '0002_term_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Przychodnia.customer'),
        ),
    ]
