# Generated by Django 3.2.13 on 2022-08-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Przychodnia', '0003_alter_term_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Przychodnia.customer'),
        ),
    ]
